name: Build ALL and Publish Release
on: [push]
jobs:
  Compile-Release:
    runs-on: ubuntu-latest
    container:
      image: motolegacy/fteqw:latest
    steps:
      - name: emsdk env
        working-directory: ./
        run: |
          cp -r /emsdk/ emsdk/
          cd emsdk/
          ls
          . emsdk_env.sh
      - uses: actions/checkout@v2
      - name: Build
        working-directory: ./
        run: |
          cd tools/
          sh build-nzp-web.sh
      - name: Generate Build Date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H-%M-%S')"
      - name: Delete Old Release
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true
          tag_name: bleeding-edge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release
        uses: softprops/action-gh-release@v1
        continue-on-error: true
        id: attempt-1
        with:
          name: Automated Release ${{ steps.date.outputs.date }}
          tag_name: bleeding-edge
          body: |
            This is a **bleeding edge** NZ:P FTE release, stability is not guarenteed.

            To install:
            - Grab the .ZIP archive for your platform.
            - Extract the contents of the .ZIP archive to your game directory (place where you have the 'nzp' folder).
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            ./tmp/pc-nzp-linux32.zip
            ./tmp/pc-nzp-linux64.zip
            ./tmp/pc-nzp-linux_arm64.zip
            ./tmp/pc-nzp-linux_armhf.zip
            ./tmp/pc-nzp-win32.zip
            ./tmp/pc-nzp-win64.zip
            ./tmp/pc-nzp-web.zip
      - name: Release attempt 2
        uses: softprops/action-gh-release@v1
        continue-on-error: true
        id: attempt-2
        if: steps.attempt-1.outcome == 'failure'
        with:
          name: Automated Release ${{ steps.date.outputs.date }}
          tag_name: bleeding-edge
          body: |
            This is a **bleeding edge** NZ:P FTE release, stability is not guarenteed.

            To install:
            - Grab the .ZIP archive for your platform.
            - Extract the contents of the .ZIP archive to your game directory (place where you have the 'nzp' folder).
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            ./tmp/pc-nzp-linux32.zip
            ./tmp/pc-nzp-linux64.zip
            ./tmp/pc-nzp-linux_arm64.zip
            ./tmp/pc-nzp-linux_armhf.zip
            ./tmp/pc-nzp-win32.zip
            ./tmp/pc-nzp-win64.zip
            ./tmp/pc-nzp-web.zip
      - name: Release attempt 3
        uses: softprops/action-gh-release@v1
        continue-on-error: true
        id: attempt-3
        if: steps.attempt-2.outcome == 'failure'
        with:
          name: Automated Release ${{ steps.date.outputs.date }}
          tag_name: bleeding-edge
          body: |
            This is a **bleeding edge** NZ:P FTE release, stability is not guarenteed.

            To install:
            - Grab the .ZIP archive for your platform.
            - Extract the contents of the .ZIP archive to your game directory (place where you have the 'nzp' folder).
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            ./tmp/pc-nzp-linux32.zip
            ./tmp/pc-nzp-linux64.zip
            ./tmp/pc-nzp-linux_arm64.zip
            ./tmp/pc-nzp-linux_armhf.zip
            ./tmp/pc-nzp-win32.zip
            ./tmp/pc-nzp-win64.zip
            ./tmp/pc-nzp-web.zip
      - name: Release attempt 4
        uses: softprops/action-gh-release@v1
        continue-on-error: true
        id: attempt-4
        if: steps.attempt-3.outcome == 'failure'
        with:
          name: Automated Release ${{ steps.date.outputs.date }}
          tag_name: bleeding-edge
          body: |
            This is a **bleeding edge** NZ:P FTE release, stability is not guarenteed.

            To install:
            - Grab the .ZIP archive for your platform.
            - Extract the contents of the .ZIP archive to your game directory (place where you have the 'nzp' folder).
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            ./tmp/pc-nzp-linux32.zip
            ./tmp/pc-nzp-linux64.zip
            ./tmp/pc-nzp-linux_arm64.zip
            ./tmp/pc-nzp-linux_armhf.zip
            ./tmp/pc-nzp-win32.zip
            ./tmp/pc-nzp-win64.zip
            ./tmp/pc-nzp-web.zip
      - name: Release attempt 5
        uses: softprops/action-gh-release@v1
        continue-on-error: false
        id: attempt-5
        if: steps.attempt-4.outcome == 'failure'
        with:
          name: Automated Release ${{ steps.date.outputs.date }}
          tag_name: bleeding-edge
          body: |
            This is a **bleeding edge** NZ:P FTE release, stability is not guarenteed.

            To install:
            - Grab the .ZIP archive for your platform.
            - Extract the contents of the .ZIP archive to your game directory (place where you have the 'nzp' folder).
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            ./tmp/pc-nzp-linux32.zip
            ./tmp/pc-nzp-linux64.zip
            ./tmp/pc-nzp-linux_arm64.zip
            ./tmp/pc-nzp-linux_armhf.zip
            ./tmp/pc-nzp-win32.zip
            ./tmp/pc-nzp-win64.zip
            ./tmp/pc-nzp-web.zip

